### ISSUE TITLE
Heroku Deployment Crashed

### ISSUE THREAD

**Issue by S2606** [fossasia/query-server#220] opened 2017-10-01 14:07 UTC
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

This happened when I asked for a JSON query to google.

![image](https://user-images.githubusercontent.com/18497513/31055402-f2353a92-a6df-11e7-9e8e-cfa79e74367d.png)

I would like to work on this

**Comment by S2606** [comment] 2017-10-01 14:07
@AnshulMalik @gabru-md ..

**Comment by niranjan94** [comment] 2017-10-01 14:39
<img width="1680" alt="screen shot 2017-10-01 at 8 08 57 pm" src="https://user-images.githubusercontent.com/2404372/31055694-61d87df6-a6e4-11e7-83a8-dc3d37db40cd.png">

Unable to reproduce for now. Closing this until either of the following happens:
- More info and proper steps to reproduce if this is an edge-case
- The bug resurfaces randomly

**Closed by niranjan94** 2017-10-01 14:39 UTC

**Comment by AnshulMalik** [comment] 2017-10-01 15:07
It was resolved in https://github.com/fossasia/query-server/pull/214
