### ISSUE TITLE
Would there be an objection to going Python 3 only?

### ISSUE THREAD

**Issue by cclauss** [fossasia/query-server#391] opened 2017-12-14 22:46 UTC
**I'm submitting a ...**
- [X] Question

When debugging app/server.py and scrapers, one of the issues that seems to come up often is the difference between bytes and strings and Unicode in Python 2.  Given that our users are often interested in making queries using double byte languages from Asia, would we better off to shift to Python 3 where every str is Unicode and where there is an explicit difference between bytes and strings?

I am fine if the answer is no.

**Comment by ParthS007** [comment] 2018-01-15 10:54
Yes, @cclauss  I agree with you, we should shift to Python 3 so that we don't have to run build for python 2 and 3 both and It's necessary to adopt the changes and there should be uniformity in the whole project. I would also like to work with you on this. Sorry for late response.

**Comment by vaibhavsingh97** [comment] 2018-01-15 11:02
@ParthS007 IMO, I think query server should support Python 2.x. As Python Community will drop suport of Python 2 by 2020 so we should atleast give support till that time.

**Comment by cclauss** [comment] 2018-01-15 11:10
Django (arguably the most used Python server platform) has dropped Python 2 support.  I believe that we can follow suit.

**Comment by ParthS007** [comment] 2018-01-15 13:39
@vaibhavsingh97  IMO Python 3 will increase uniformity in the project as some scripts are in Python 2 or 3 presently. One version should be present in whole projects and we can't downgrade it to Python 2 so only Python 3 is the only alternative.

**Comment by cclauss** [comment] 2018-01-21 14:38
@ParthS007 What do you view as the next steps on this issue?

**Comment by mariobehling** [comment] 2018-09-03 05:43
Duplicate of https://github.com/fossasia/query-server/issues/508

**Closed by mariobehling** 2018-09-03 05:43 UTC
