### ISSUE TITLE
Add Youtube support

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/query-server#290] opened 2017-10-28 20:44 UTC
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Yes, I would like to work on this issue**

**Comment by cclauss** [comment] 2017-11-02 02:12
Duplicate of #139 ?

**Closed** 2017-11-02 16:24 UTC
Labels: has-PR
