### ISSUE TITLE
Heroku Deployment not working

### ISSUE THREAD

**Issue by ms10398** [fossasia/query-server#190] opened 2017-09-25 05:54 UTC
When visiting this link[https://query-server.herokuapp.com/] 
It shows application error 

**Screenshot is below**

![screenshot from 2017-09-25 11-21-30](https://user-images.githubusercontent.com/26259547/30794100-e74f519a-a1e3-11e7-87f3-8746141c7b0c.png)

**Comment by aviaryan** [comment] 2017-09-25 16:51
Duplicate of #184

**Comment by vaibhavsingh97** [comment] 2017-09-25 17:06
I am claiming issue this issue

**Comment by cclauss** [comment] 2017-09-26 09:22
Duplicate of #184 ?

**Comment by bhaveshAn** [comment] 2017-09-26 12:35
I would like to work on this issue. May I ?

**Comment by ms10398** [comment] 2017-09-26 12:51
I think there is already @vaibhavsingh97 working on it

**Comment by bhaveshAn** [comment] 2017-10-27 18:16
Please close this one !

**Closed** 2017-10-28 00:53 UTC
