### ISSUE TITLE
Ask.com internal server error

### ISSUE THREAD

**Issue by S2606** [fossasia/query-server#304] opened 2017-11-02 06:38 UTC
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**
![image](https://user-images.githubusercontent.com/18497513/32312963-8365bec0-bfc6-11e7-9544-946692b1f363.png)

**Expected behavior:**
It should work!

**Comment by shashank-sharma** [comment] 2017-11-02 07:00
Similar to #279

**Comment by niranjan94** [comment] 2017-11-02 07:02
Duplicate of #279

**Closed** 2017-11-02 07:02 UTC
